name: 'Terragrunt Infrastructure'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  plan:
    name: 'Terragrunt Plan'
    runs-on:
  workflow_dispatch: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TERRAGRUNT_WORKING_DIR: infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::496411573458:role/sumesh-github-actions-aws-role
        aws-region:
  workflow_dispatch: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version:
  workflow_dispatch: 1.9.0
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v3
      with:
        terragrunt-version:
  workflow_dispatch: 0.66.0

    - name: Terragrunt Init
      run: terragrunt run-all init --terragrunt-non-interactive
      working-directory: ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive
      working-directory: ${{ env.TERRAGRUNT_WORKING_DIR }}

  apply:
    name: 'Terragrunt Apply'
    runs-on:
  workflow_dispatch: ubuntu-latest
    needs: plan
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      AWS_REGION: us-east-1
      TERRAGRUNT_WORKING_DIR: infrastructure
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::496411573458:role/sumesh-github-actions-aws-role
        aws-region:
  workflow_dispatch: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version:
  workflow_dispatch: 1.9.0
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v3
      with:
        terragrunt-version:
  workflow_dispatch: 0.66.0

    - name: Terragrunt Init
      run: terragrunt run-all init --terragrunt-non-interactive
      working-directory: ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Apply
      run: terragrunt run-all apply --terragrunt-non-interactive
      working-directory: ${{ env.TERRAGRUNT_WORKING_DIR }}
